fix: ci
add environment variable

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -76,13 +76,17 @@ jobs:
       - name: Build with Next.js
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
       - name: Create index.html
+        env:
+          INPUT_PATH: ./out
         run: |
-          cd out || exit 1
           if [ -f "index.html" ]; then
             exit 0
           elif [ -f "en.html" ]; then
             cp en.html index.html
             exit 0
+          else
+            echo "missing index.html"
+            exit 1
           fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
